language: java

before_install:
 - chmod +x gradlew
 - mkdir -p src/main/resources
 - echo "" > src/main/resources/version.properties
 
script:
 - ./gradlew clean check test fatCapsule

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "hbF1Gfew15wgSpaUfxtoW0NP/HPAbe0jSpPRcw8TZMYNtlC5zQPrhy1V7EJXOD4T1v0xjbNUyVGPQxyF7eKcOtemjQOlQjKgOt8qwtDIWL/92la235KZrubCrGRFh4zlpXCRWhG2p3Ki7tRueZs/Og4PIxqoKlN7Z+jVGFtVI2CPz4Y9jnU6uAdj9Q/xKlt2CoWY/Xw54s66+9HZaVRJLWoS2L5BOXLmdSJRxoPvnWYIewxjt5sr7KfFF94XbqQee432djNMQkxRmV6/vFPV28IlZ6oNFpA2pSkgb+uq/LD3K2+1fdttcHFPHs5yExSv0zKk75gev5ywooNOTjgap08hYs3o4w+DVkcI2MoISXwW8viW7OHbrYm6fRTTHfTkz6PKjYDnmNvYL5yAE1p07IEKeSfaaQw1LmJZ8xp8xt80TLGHOlp7By5wZyuzesYku19YnD5optRQ8HMqq155xfJg/eRlbSrRp/i8vnPBNqVjHWPgjWUAkobfZyy+hN/nDqf/+YIlOd+UX8aXTcYQf0CcUsd8DoXrUxJpJwEv4L9H7mzopywqbgBs1y3iHUC5xHxTVXHCBoKiK/p4oUlABE65yqxI9O750HWVaaT0RubqfjSTEVbYj9udKSJuItyP1dCsSBIYyTKYe1FXo20wel3WQzaIyonAylJh/krYqGo="
  file:
    - "build/libs/Wingman.jar"
    - "build/libs/Wingman-capsule.jar"
  on:
    tags: true
